#!/usr/bin/env bash
# Build the embedded stylesheet from internal/ui/input.css into
# static/css/app.css. Shared by `make generate` and scripts/build.sh so CSS is
# regenerated by every generate-dependent target (test/lint/vet/e2e), surfacing
# drift immediately instead of only at build time.
set -euo pipefail
cd "$(dirname "$0")/.."

# Locate a Tailwind CLI: prefer the vendored standalone binary, then one on
# PATH, else fall back to the node package (npx) since node is a dev dep.
if [ -x ./bin/tailwindcss ]; then
	TAILWIND=(./bin/tailwindcss)
elif command -v tailwindcss >/dev/null 2>&1; then
	TAILWIND=(tailwindcss)
else
	TAILWIND=(npx --yes @tailwindcss/cli)
fi

"${TAILWIND[@]}" -i internal/ui/input.css -o static/css/app.css --minify
